config/routes.rb
Rails.application.routes.draw do
 

  resources :customers
  root "customers#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/customer.rb
class Customer < ApplicationRecord
    validates :name, presence: true, format: { with: /\A[a-zA-Z]+\z/},length: {in: 2..50}
    validates :age, presence: true, numericality: {in: 8..99}
    validates :gender, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def index
    @customers=Customer.all.order(created_at: :desc)
  end

  def new
  
    @customer=Customer.new
  end

  def create
    @customer = Customer.new(customer_params)
    if @customer.save
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @customer=Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    
    if @customer.update(customer_params)
      redirect_to root_path, status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end
  def destroy
    @customer = Customer.find(params[:id])
    @customer.destroy

    redirect_to root_path, status: :see_other
    
  end

  private

  def customer_params
    params.require(:customer).permit(:name, :age, :gender)
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def index
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/customers/_form.html.erb
<%= form_with model: @customer do |form| %>
    <div>
      <%= form.label :name  %>
      <%= form.text_field :name %>
      <% @customer.errors.full_messages_for(:name ).each do |message| %>
        <div class="error"><%= message %></div>
      <% end %>
      
    </div>
  
    <p>
      <%= form.label :age %>
      <%= form.text_field:age %>
      <% @customer.errors.full_messages_for(:age ).each do |message| %>
        <div class="error"><%= message %></div>
      <% end %>
    </p>
    
    <div class=radio>
    
        <%= form.label :gender %>
        <%= form.radio_button :gender, 'male' %>
        <%= form.label :gender, value: 'male' %>
        <%= form.radio_button :gender, 'female' %>
        <%= form.label :gender, value: 'female' %>
        <% @customer.errors.full_messages_for(:gender ).each do |message| %>
          <div class="error"><%= message %></div>
        <% end %>
    </div>
   
    <p>
      <%= form.submit 'submit' %>
    </p>
    
<% end %>

app/views/customers/create.html.erb
<h1>Customers#create</h1>
<p>Find me in app/views/customers/create.html.erb</p>

app/views/customers/edit.html.erb
<h1>Customers#edit</h1>
<%= render "form", customer: @customer %>

app/views/customers/index.html.erb
<html>
<head>
<%= stylesheet_link_tag "application" %>
</head>
<body>
<h1>Customers#index</h1>


<table>
<thead>
<tr>
<th>Name</th>
<th>Age</th>
<th>Gender</th>
<th>Edit</th>
<th>Delete</th>
</tr>
</thead>
<tbody>
<% @customers.each do |c| %>
<tr>
    <td><%= c.name %></td>
    <td><%= c.age %></td>

    <td><%= c.gender %></td>
    <td><%= link_to "Edit", edit_customer_path(c) %></td>
    <td><%= link_to "Destroy", customer_path(c), data: {
        turbo_method: :delete,
        turbo_confirm: "Are you sure?"
      } %></td>

    
</tr>
<%end%>
</tbody>
</table>
<div class="link">
<%= link_to "New Customer", new_customer_path %>
</div>


</body>
</html>

app/views/customers/new.html.erb
<h1>Registration Form</h1>

<%= render "form", customer: @customer %>

app/views/customers/update.html.erb
<h1>Customers#update</h1>
<p>Find me in app/views/customers/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mvctest</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/user/create.html.erb
<h1>User#create</h1>
<p>Find me in app/views/user/create.html.erb</p>

app/views/user/edit.html.erb
<h1>User#edit</h1>
<p>Find me in app/views/user/edit.html.erb</p>

app/views/user/index.html.erb
<h1>User#index</h1>
<p>Find me in app/views/user/index.html.erb</p>

app/views/user/new.html.erb
<h1>User#new</h1>
<p>Find me in app/views/user/new.html.erb</p>

app/views/user/update.html.erb
<h1>User#update</h1>
<p>Find me in app/views/user/update.html.erb</p>